=== ech-tink-er/telerik-academy/11. Databases/Homework/02. XML Basics/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="urn:students"
    elementFormDefault="qualified"
    xmlns="urn:schema"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <!--structure-->
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{15}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="course" type="xs:string"/>
              <xs:element name="speciality" type="xs:string"/>
              <xs:element name="exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="exam" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="tutor" type="xs:string"/>
                          <xs:element name="score">
                              <xs:simpleType>
                                <xs:restriction base ="xs:decimal">
                                  <xs:minInclusive value="0"/>
                                  <xs:maxInclusive value="100"/>
                                  <xs:fractionDigits value="2"/>
                                </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="submission">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="date" type="xs:date"/>
                    <xs:element name="score">
                        <xs:simpleType>
                        <xs:restriction base ="xs:decimal">
                          <xs:minInclusive value="0"/>
                          <xs:maxInclusive value="100"/>
                          <xs:fractionDigits value="2"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="comment" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="faculty-number">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[0-9]{4,}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birth-date" type="xs:date"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ech-tink-er/telerik-academy/11. Databases/Homework/02. XML Basics/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xslt"?>
<st:students xmlns:st="urn:students"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:students students.xsd">

	<st:student faculty-number="112334" birth-date="1993-09-24">
		<st:name>John</st:name>
		<st:gender>male</st:gender>
		<st:phone>123456789012345</st:phone>
		<st:email>john@doe.com</st:email>
		<st:course>Programming</st:course>
		<st:speciality>C#</st:speciality>
		<st:exams>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
		</st:exams>
		<st:submission>
			<st:date>2015-01-17</st:date>
			<st:score>78</st:score>
			<st:comment>noice</st:comment>
		</st:submission>
	</st:student>
	<st:student faculty-number="112334" birth-date="1993-09-24">
		<st:name>Anna</st:name>
		<st:gender>male</st:gender>
		<st:phone>123456789012345</st:phone>
		<st:email>john@doe.com</st:email>
		<st:course>Programming</st:course>
		<st:speciality>C#</st:speciality>
		<st:exams>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
		</st:exams>
		<st:submission>
			<st:date>2015-01-17</st:date>
			<st:score>78</st:score>
			<st:comment>noice</st:comment>
		</st:submission>
	</st:student>
	<st:student faculty-number="112334" birth-date="1993-09-24">
		<st:name>Steven</st:name>
		<st:gender>male</st:gender>
		<st:phone>123456789012345</st:phone>
		<st:email>john@doe.com</st:email>
		<st:course>Programming</st:course>
		<st:speciality>C#</st:speciality>
		<st:exams>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
		</st:exams>
		<st:submission>
			<st:date>2015-01-17</st:date>
			<st:score>78</st:score>
			<st:comment>noice</st:comment>
		</st:submission>
	</st:student>
	<st:student faculty-number="112334" birth-date="1993-09-24">
		<st:name>Danny</st:name>
		<st:gender>male</st:gender>
		<st:phone>123456789012345</st:phone>
		<st:email>john@doe.com</st:email>
		<st:course>Programming</st:course>
		<st:speciality>C#</st:speciality>
		<st:exams>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
		</st:exams>
		<st:submission>
			<st:date>2015-01-17</st:date>
			<st:score>78</st:score>
			<st:comment>noice</st:comment>
		</st:submission>
	</st:student>
	<st:student faculty-number="112334" birth-date="1993-09-24">
		<st:name>Beth</st:name>
		<st:gender>male</st:gender>
		<st:phone>123456789012345</st:phone>
		<st:email>john@doe.com</st:email>
		<st:course>Programming</st:course>
		<st:speciality>C#</st:speciality>
		<st:exams>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
			<st:exam>
				<st:name>C# Basic</st:name>
				<st:tutor>Thor</st:tutor>
				<st:score>7</st:score>
			</st:exam>
		</st:exams>
		<st:submission>
			<st:date>2015-01-17</st:date>
			<st:score>78</st:score>
			<st:comment>noice</st:comment>
		</st:submission>
	</st:student>
</st:students>
